[package]
name = "lox_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug_trace_execution = []
debug_print_code = []

[dependencies]
rustyline = "9.1"
